### ISSUE TITLE
Add support for reduced feature sets.

### ISSUE THREAD

**Issue by bader** [KhronosGroup/SYCL-CTS#365]
A number of SYCL-CTS tests require "full" feature set. For instance, multi_ptr test requires implementation to support generic address space and id test requires implementation to support unnamed SYCL kernel function feature.

**Comment by fraggamuffin** [comment]
should we have flag to switch between full and reduce? 
is reduced feature set real? Need feedback from CP.

**Comment by alycm** [comment]
Below is the current state of reduced feature set support on ComputeCpp to provide some context.  Answering based on the using the "experimental" ComputeCpp compiler, which is where the primary SYCL 2020 support is being developed.

**Un-named SYCL kernel functions**.   ComputeCpp can support unnamed lambas when using ComputeCpp as both the host and device compiler.  For using a separate host compiler it depends on whether you get lucky with how that compiler's ABI encodes lambda names.  I suspect that the program will compile without error, but then it _might_ not run.  There is currently no flag to force this support off.

**Address space mode**.  ComputeCpp is always compiling programs using the inferred address space mode, even if the target hardware can support the generic address space.  If a program violates the inferred address space rules then ComputeCpp will fail to compile the program with some kind of "Address space conflict" error.  This will happen for very few programs.  There is no flag for this because ComputeCpp currently only supports the single mode.

There is a third point in the reduced feature set, but it's taking me a little longer to understand that part.
