### ISSUE TITLE
Commit "add tests for common reference semantics" fails CTS compilation on CUDA with DPCPP

### ISSUE THREAD

**Issue by dm-vodopyanov** [KhronosGroup/SYCL-CTS#510]
Guilty commit: https://github.com/KhronosGroup/SYCL-CTS/commit/4c073ce18ab056e1b1deb6a6cb27801b31339449 (might be not the only one)

Logs: https://github.com/intel/llvm/actions/runs/4129760637/jobs/7136039243

@nolmoonen could you please take a look?

@bader, FYI

**Comment by nolmoonen** [comment]
From the linked log, it looks to me that the recently added test category `image_accessor` has not yet been added to the CI filter that is passed with `SYCL_CTS_EXCLUDE_TEST_CATEGORIES` (which is [devops/cts_exclude_filter](https://github.com/intel/llvm/blob/sycl/devops/cts_exclude_filter) as far as I can tell). This test category is added in https://github.com/KhronosGroup/SYCL-CTS/pull/485.

Next to adding `image_accessor`, I would suggest to add `math_builtin_api` so that the [CTS CI filter file](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/ci/dpcpp.filter) is a subset of the DPCPP filter file (disregarding `buffer`, since that seems to work with DPCPP). The test category `math_builtin_api` is recently disabled for DPCPP in the CTS as this test now has increased coverage, causing compilation for DPCPP to break. The PR that extends that coverage is https://github.com/KhronosGroup/SYCL-CTS/pull/499.

**Comment by dm-vodopyanov** [comment]
@nolmoonen, thanks a lot!
