### ISSUE TITLE
Possible errors in `accessor_legacy` tests

### ISSUE THREAD

**Issue by nilsfriess** [KhronosGroup/SYCL-CTS#536]
Hello,

I am currently trying to compile the `accessor_legacy` test with Open SYCL (previously known as hipSYCL) and I am getting a number of compile errors where I am not 100% sure if it is an error in the CTS or in Open SYCL.

In the tests, there are a number of constructs that essentially boil down to this: There is a templated function of the following form
```
template <typename T>
void foo() {
  auto val = static_cast<T>(42);
}
```
and the this function is then called with various types for `T`, in particular with `sycl::vec`s, for example
```
  using type = sycl::vec<float, 2>;
  foo<type>();
```
One example can be found [here](https://github.com/KhronosGroup/SYCL-CTS/blob/SYCL-2020/tests/accessor_legacy/accessor_api_common_buffer_local.h#L232).

This leads to a compile error because according to the specification, the constructor of a `sycl::vec` that only takes a single argument of type `const DataT&` (the type of the elements that the `vec` holds) is marked explicit. However, in most of the cases (as in the example above), the type of the argument (`42` in this example) and the type of the `vec`'s elements (`float` in this example) do not match. 

This could be solved by introducing a type trait that checks if `T` is a `sycl::vec` and, if `T` is indeed a `sycl::vec`, replacing the line in the example above by something like 
```
auto val = T(static_cast<typename T::element_type>(42));
```
i.e., explicitly casting the argument to the correct type before calling the constructor. 

My question basically is whether or not I correctly understand the spec, i.e., if something like the example above should compile according to the spec or not.

**Comment by gmlueck** [comment]
I don't know why the OpenSYCL implementation gives an error for this code, but my understanding is that it should work even though the `vec` constructor has the `explicit` keyword.  I think this is because `static_cast` performs "direct initialization" rather than "copy initialization", and "direct initialization" considers all constructors (even those marked `explicit`).

https://en.cppreference.com/w/cpp/language/direct_initialization
https://en.cppreference.com/w/cpp/language/explicit

FWIW, the DPC++ implementation does mark this `vec` constructor as `explicit`.

**Comment by nilsfriess** [comment]
Thanks for clearing that up, you're right, it should work and I think I understand now why it doesn't work in OpenSYCL.
